[package]
name = "scrypt-ocl"
version = "0.8.0"
edition = "2021"

[dependencies]
ocl = "0.19.7"
thiserror = "1.0.68"
post-rs = { path = "../" }
log = "0.4.22"
regex = "1.11.1"

[dev-dependencies]
post-rs = { path = "../" }
rstest = "0.22.0"
