[package]
name = "scrypt-ocl"
version = "0.7.6"
edition = "2021"

[dependencies]
ocl = "0.19.4"
thiserror = "1.0.57"
post-rs = { path = "../" }
log = "0.4.17"
regex = "1.10.4"

[dev-dependencies]
post-rs = { path = "../" }
rstest = "0.18.2"
